### PR TITLE
Adding Whedon preview service

### PR DESCRIPTION
**Pull request by arfon**
This is a simple extension to the whedon-api web application that allows an author to test the compilation of their JOSS or JOSE papers.

Accessing the web service at [`http://whedon.theoj.org`](http://whedon.theoj.org/), a user can specify a Git repository address (http format), and choose whether to produce a JOSS or JOSE preview.

Screen Shot 2019-10-13 at 9 47 07 PM
Screen Shot 2019-10-13 at 9 47 26 PM

- Fixes openjournals/joss#553
- Fixes openjournals/joss#379 
- Fixes openjournals/joss#370
- Fixes openjournals/whedon#17

/ cc @openjournals/joss-editors @openjournals/jose-eics

### CODE REVIEW

**Comment by labarba** [comment]
Hmm. I just tried it with this repo, and it failed
https://github.com/barbagroup/CFDPython

Screen Shot 2019-10-13 at 5 08 42 PM

**Comment by arfon** [comment]
> Hmm. I just tried it with this repo, and it failed

@labarba try again now?

**Comment by labarba** [comment]
It worked!

Note that I selected the JOSE radio button, but the fake DOI on the margin decorators showed joss instead.

**Comment by cMadan** [comment]
I think this is great! Worked well in a quick test, though the authors in the footer citation showed as "Mickey Mouse". (I assume still in-progress, but thought I'd flag that.)

**Comment by cscherrer** [comment]
For me it says it worked, but instead of a preview the link takes me to a page that just says "Not found" 

repo: https://github.com/cscherrer/writing/2019-JOSS
branch: dev

**Comment by arfon** [comment]
This is because `https://github.com/cscherrer/writing/2019-JOSS` is not visible to Whedon - is this private?

**Comment by cscherrer** [comment]
Sorry, I think I had mistyped that. Actual page is here:
https://github.com/cscherrer/Soss.jl/tree/dev/writing/2019-JOSS

**Comment by arfon** [comment]
Ah OK. The first parameter should just be the repository address (`https://github.com/cscherrer/Soss.jl`).

Also, in this case, I think it's failing because your `paper.md` is referencing `bibliography.bib` in the YAML header but your bibtex is actually called `paper.bib`.

Producing more reliable errors is definitely something we need to work on here...

**Comment by cscherrer** [comment]
That fixes it, thank you @arfon !

**Comment by ekiefl** [comment]
image

The website seems to be down :\

**Comment by arfon** [comment]
@ekiefl – apologies, but this service is pretty much deprecated now, and has been replaced by https://github.com/openjournals/openjournals-draft-action

**Pull request merged**
