### PR TITLE
Multi-journal Whedon API

### PR DESCRIPTION
**Pull request by parrish**
@arfon This is for openjournals/whedon-api#8 and is currently deployed on staging too.

Thanks!

### CODE REVIEW

**Comment by arfon** [comment]
⚡️ this looks really good @parrish. One thing I've spotted here is that the JOSS application URL is still [hardcoded in here](https://github.com/openjournals/whedon-api/pull/11/files#diff-61dc6944d03f4f1695a11947c20e4a90R207), we should be extracting that into the config too right?

**Comment by parrish** [comment]
Yep, good spot!

**Comment by parrish** [comment]
I've got the deploy updated with the latest commits.  Pretty sure this is good to go.

Also, we'll have to remember after the merge that this is switching from `secrets.yml` to `.env`.

**Comment by arfon** [comment]
Closing in favour of #12

**Pull request closed without merging**
